envtalana/core/core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from mascotas.views import upload, home, like_post

urlpatterns = [
    path('admin/', admin.site.urls),
    path('upload/', upload, name='upload'),
    path('', home, name='home'),
    url(r'^accounts/', include('allauth.urls')),
    re_path('like/(?P<nickname>[a-zA-Z0-9.-]+)', like_post, name="like_post"), 





    
]

urlpatterns += static("/media/", document_root=settings.MEDIA_ROOT)

envtalana/core/mascotas/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Post(models.Model):
    model_pic = models.ImageField(upload_to = 'pic_folder/', default = 'pic_folder/None/no-img.jpg')
    nickname = models.CharField(max_length=250)
    name_pets = models.CharField(max_length=250)
    likes = models.IntegerField(default=0)

    def __str__(self):
          return self.nickname

envtalana/core/mascotas/forms.py
from django import forms


class ImageUploadForm(forms.Form):
    image = forms.ImageField()
    nickname = forms.CharField(max_length=250)
    name_pets = forms.CharField(max_length=250)

envtalana/core/mascotas/views.py
from django.shortcuts import render, redirect, get_object_or_404

from django.http import HttpResponse
from .models import Post
from .forms import ImageUploadForm
from django.db.models import F

# Create your views here.

def upload(request):
    if request.method == 'POST':
        form = ImageUploadForm(request.POST, request.FILES)
        if form.is_valid():
            model_pic = form.cleaned_data['image']
            nickname = form.cleaned_data['nickname']
            name_pets = form.cleaned_data['name_pets']
            m = Post.objects.get_or_create(model_pic=model_pic, nickname=nickname,name_pets=name_pets)
            return redirect('/')
    elif request.method == 'GET':
          return render(request,'upload.html')     

def home(request):
    example = Post.objects.all()
    context = {
        'example': example,

    }
    return render(request,'home.html', context)

def like_post(request, nickname):
     print(nickname)
     #post = get_object_or_404(Post, nickname=nickname)
     Post.objects.filter(nickname=nickname).update(likes=F('likes') + 1)
     return redirect('/')

   #

envtalana/core/templates/base.html
{% load static %}



<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>
        {% block head_title %}

         {% endblock %}
    </title>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>


<body>
    <div style="padding-bottom:80px"></div>

    {% block content %}

    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <!-- Bootstrap tooltips -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <!-- Bootstrap core JavaScript -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>


</html>

envtalana/core/templates/home.html
{% extends "base.html" %}
{% load static %}


{% block content %}

<section class="text-center mb-4">
     <div class="row wow fadeIn">

       {% for item in example %}
           <div class="col-lg-3 col-md-6 mb-4">
             <div class="card mb-3 zoom">

                 <a href="#">
                     <div class="view overlay">
                         <img height="250px" src="{{ item.model_pic.url }}" class="card-img-top">
                     </div>

                     <div class="card-body text-center">
                       <h5>
                         <strong>
                              nickname : {{item.nickname}}
                         </strong>

                         <strong>
                              mascota : {{item.name_pets}}
                         </strong>
                       </h5>
                 </a>

                 <p>tienes {{item.likes}} votos </p>
                 <div class="text-warning" style="font-size:0.7rem">
                     <span class="fa fa-star">
                     </span>
                     <span class="fa fa-star">
                     </span>
                     <span class="fa fa-star">
                     </span>
                     <span class="fa fa-star">
                     </span>
                     <span class="fa fa-star">
                     </span>
                 </div>
                 <form action="{% url 'like_post' item.nickname %}" method="post">
                    {% csrf_token %}
                    <button type="submit" name="post_id" value="{{post_id}}" class="btn btn-primary">Votar</button>
                 </form>
               </div>

             </div>

         </div>
             {% endfor %}

   </section>


   
        {% endblock %}

   

envtalana/core/templates/upload.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<form action="/upload/" method="post" enctype="multipart/form-data">{% csrf_token %}
     <p>
         <input id="id_image" type="file" class="" name="image">
     </p>
     <p>
        <input id="id_nickname" type="text" class="" name="nickname">
    </p>
    <p>
        <input id="id_name_pets" type="text" class="" name="name_pets">
    </p>
     <input type="submit" value="Submit" />
</form>

{% endblock %}